module.exports = [
    {short:"  ", name:"Please select your major"},
    {short:"SPTAB" , name:"Accelerated BS/DPT in Physical Therapy"},
    {short:"ACCT" , name:"Accounting"},
    {short:"ACTNG" , name:"Acting"},
    {short:"AJAUC" , name:"Administration of Justice BA"},
    {short:"AJAUC" , name:"Administration of Justice BS"},
    {short:"AERSP" , name:"Aerospace Engineering"},
    {short:"AFRST" , name:"African Studies"},
    {short:"AGBM" , name:"Agribusiness Management"},
    {short:"AEE" , name:"Agricultural & Extnesion Education"},
    {short:"AGSC" , name:"Agricultural Science"},
    {short:"AMSCA" , name:"American Studies"},
    {short:"ANSC" , name:"Anumal Science"},
    {short:"ANTH" , name:"Antrhopology"},
    {short:"AE" , name:"Architectural Engineering"},
    {short:"ARTAB" , name:"Art"},
    {short:"AED" , name:"Art Education"},
    {short:"ARTH" , name:"Art History"},
    {short:"ARTSA" , name:"Art Administration"},
    {short:"ASIA" , name:"Asian Studies"},
    {short:"ASTRO" , name:"Astronomy and Astrophysics"},
    {short:"ATHTR" , name:"Athletic Training"},
    {short:"BBH" , name:"Biobehaviroal Health"},
    {short:"BMB" , name:"Biohemistry and Molecular Biology"},
    {short:"BE" , name:"Biological Engineering"},
    {short:"BIO" , name:"Biology"},
    {short:"BME" , name:"Biomedical Engineering"},
    {short:"BRS" , name:"Biorenewable Systems"},
    {short:"BIOTC" , name:"Biotechnology"},
    {short:"BS" , name:"Business"},
    {short:"BECON" , name:"Business Economics"},
    {short:"CHE" , name:"Chemical Engineering"},
    {short:"CHEM" , name:"Chemistry"},
    {short:"CHNS" , name:"Chinese"},
    {short:"CE" , name:"Civil Engineering"},
    {short:"CAMS" , name:"Classics and Ancient Mediterranean Studies"},
    {short:"COMM" , name:"Communications"},
    {short:"CED" , name:"Community, Environment and Development"},
    {short:"CMLIT" , name:"Comparitive Literature"},
    {short:"CMPEN" , name:"Computer Engineering"},
    {short:"CMPSC" , name:"Computer Science"},
    {short:"CCBA" , name:"Corporate Communications"},
    {short:"CIENT" , name:"Corporate Innovation and Enterprenuership"},
    {short:"CWRIT" , name:"Creative Writing"},
    {short:"CRIMJ" , name:"Criminal Justice"},
    {short:"CRMBS" , name:"Criminology"},
    {short:"CYAOP" , name:"Cybersecurity Analytics and Operations"},
    {short:"DATSC" , name:"Data Sciences, Applied Data Sciences"},
    {short:"DGJRM" , name:"Digital Journalism and Media"},
    {short:"DIGIT" , name:"Digital Media, Arts, and Technology"},
    {short:"DIGMD" , name:"Digital Multimedia Design"},
    {short:"DUS" , name:"Divison of Undergraduate Studies"},
    {short:"EMSC" , name:"Earth & Mineral Sciences"},
    {short:"EARTH" , name:"Earth Sciences"},
    {short:"ECLBS" , name:"Economics"},
    {short:"EPP" , name:"Education and Public Policy"},
    {short:"ECET" , name:"Electrical and Computer Engineering Technology"},
    {short:"EE" , name:"Electrical Engineering"},
    {short:"EET" , name:"Electrical Engineering Technology"},
    {short:"EMET" , name:"Mechanical Engineering Technology"},
    {short:"ELEM" , name:"Elementary Education"},
    {short:"ESP" , name:"Energy and Sustainable Policy"},
    {short:"ENENG" , name:"Energy Engineering"},
    {short:"EBF" , name:"Engineering, Business and Finance"},
    {short:"ENGR" , name:"Engineering (Undecided)"},
    {short:"GE" , name:"Engineering"},
    {short:"ESC" , name:"Engineering Science"},
    {short:"ENGL" , name:"English"},
    {short:"ERM" , name:"Environmental Resource Management"},
    {short:"ENVSC" , name:"Environmental Science"},
    {short:"ENV" , name:"Enivironmental Studies"},
    {short:"ENVSE" , name:"Environmental Systems Engineering"},
    {short:"FILM" , name:"Film and Video"},
    {short:"FNC" , name:"Finance"},
    {short:"FDSC" , name:"Food Science"},
    {short:"FRNSC" , name:"Forensic Science"},
    {short:"FOREM" , name:"Forest Ecosystem Management"},
    {short:"FR" , name:"French and Frncophone Studies"},
    {short:"GAS" , name:"General Arts & Sciences"},
    {short:"GEOBI" , name:"Geobiology"},
    {short:"GEO" , name:"Geography"},
    {short:"GSC" , name:"Geosciences"},
    {short:"GER" , name:"German"},
    {short:"GS" , name:"Global and International Studies"},
    {short:"GLBST" , name:"Global Studies"},
    {short:"GHHD" , name:"Golf Management"},
    {short:"GD" , name:"Graphic Design"},
    {short:"HHD" , name:"Health and Human Development"},
    {short:"HPA" , name:"Health Policy and Administration"},
    {short:"HIST" , name:"History"},
    {short:"HM" , name:"Hospitality Managment"},
    {short:"HDFS" , name:"Human Development and Family Studies"},
    {short:"HUMN" , name:"Humanitiies"},
    {short:"IID" , name:"Immunology and Infectious Disease"},
    {short:"IE" , name:"Industrial Engineering"},
    {short:"IST" , name:"Information Sciences and Technology"},
    {short:"INFSY" , name:"Information Systems"},
    {short:"ISOSC" , name:"Integrated Social Sciences"},
    {short:"INART" , name:"Integrative Arts"},
    {short:"IBE" , name:"Interdisciplinary Business with Engineering Studies"},
    {short:"IDS" , name:"Interdisciplinary Digital Studio"},
    {short:"INTB" , name:"International Business"},
    {short:"INTPL" , name:"International Politics"},
    {short:"IT" , name:"Italian"},
    {short:"JAP" , name:"Japanese"},
    {short:"JST" , name:"Jewish Studies"},
    {short:"JOURN" , name:"Journalism"},
    {short:"KINES" , name:"Kinesiology"},
    {short:"LBE" , name:"Labor and Employment Relations"},
    {short:"LARCH" , name:"Landscape Architecture"},
    {short:"LSCPE" , name:"Landscape Contracting"},
    {short:"LATAM" , name:"Latin American Studies"},
    {short:"LAWSC" , name:"Law and Society"},
    {short:"LAS" , name:"Letters, Arts, & Sciences"},
    {short:"LA" , name:"Liberal Arts"},
    {short:"MGMT" , name:"Management"},
    {short:"MIS" , name:"Management Information Systems"},
    {short:"MRKT" , name:"Marketing"},
    {short:"MATSE" , name:"Materials Sciences & Engineering"},
    {short:"MASC" , name:"Mathematical Sciences"},
    {short:"MTH" , name:"Mathematics"},
    {short:"ME" , name:"Mechanical Engineering"},
    {short:"MET" , name:"Mechanical Engineering Technology"},
    {short:"MEDIA" , name:"Media Studies"},
    {short:"MEDVL" , name:"Medieval Studies"},
    {short:"METEO" , name:"Meteorology and Atmospheric Science"},
    {short:"MICRB" , name:"Microbiology"},
    {short:"MLVED" , name:"Middle Level Education"},
    {short:"MNGE" , name:"Mining Engineering"},
    {short:"MUS" , name:"Music"},
    {short:"MUED" , name:"Music Education"},
    {short:"MUBMA" , name:"Musical Arts"},
    {short:"THRMT" , name:"Musical Theatre"},
    {short:"NUCE" , name:"Nuclear Engineering"},
    {short:"NURS" , name:"Nursing"},
    {short:"NUTR" , name:"Nutritional Science"},
    {short:"ORPCM" , name:"Organization and Professional Communications"},
    {short:"OL" , name:"Organizational Leadership"},
    {short:"PNGE" , name:"Petroleum and Natural Gas Engineering"},
    {short:"PHIL" , name:"Philosphy"},
    {short:"PHYS" , name:"Physics"},
    {short:"PASTR" , name:"Planetary Sceince and Astronomy"},
    {short:"PLANT" , name:"Plant Sciences"},
    {short:"PLT" , name:"Plastics Engineering Technology"},
    {short:"PLSC" , name:"Political Sciences"},
    {short:"PMM" , name:"Premedical-Medical"},
    {short:"PM" , name:"Premedicine"},
    {short:"PHOTO" , name:"Professional Photography"},
    {short:"PWRIT" , name:"Professional Writing"},
    {short:"PSCM" , name:"Project and Supply Chain Management"},
    {short:"PSS" , name:"Psychological and Social Sciences"},
    {short:"PSYC" , name:"Psychology"},
    {short:"PUBPL" , name:"Public Policy"},
    {short:"RTEAL" , name:"Rail Transportation Engineering"},
    {short:"RPTM" , name:"Recreation, Park, and Tourism"},
    {short:"RHS" , name:"Rehabilitation and Human Services"},
    {short:"RM" , name:"Risk Management"},
    {short:"RUS" , name:"Russian"},
    {short:"SCIEN" , name:"Science"},
    {short:"SECED" , name:"Secondary Education"},
    {short:"SRA" , name:"Security and Risk Analysis"},
    {short:"SODA" , name:"Social Data Analytics"},
    {short:"SOC" , name:"Sociology"},
    {short:"SEBC" , name:"Software Engineering"},
    {short:"SPN" , name:"Spanish"},
    {short:"SPLED" , name:"Special Education"},
    {short:"STAT" , name:"Statistics"},
    {short:"STRCM" , name:"Strategic Communications"},
    {short:"SDCET" , name:"Stuctural Design and Construction Engr Technology"},
    {short:"SCIS" , name:"Supply Chain and Information Systems"},
    {short:"SURE" , name:"Surveying Engineering"},
    {short:"THRFA" , name:"Technical Theatre"},
    {short:"TELECM" , name:"Telecommuications"},
    {short:"THR" , name:"Theatre Studies"},
    {short:"TOX" , name:"Toxicology"},
    {short:"TURF" , name:"Turfgrass Science"},
    {short:"DUS" , name:"Undecided"},
    {short:"VBSC" , name:"Veterinary and Biomedical Sciences"},
    {short:"VAST" , name:"Visual Art Studies"},
    {short:"WFS" , name:"Wildlife and Fisheries Science"},
    {short:"WS" , name:"Woman Studies"},
    {short:"WFED" , name:"Workforce Education and Development"},
    {short:"WLED" , name:"World Languages Educations"},
]
